### ISSUE TITLE
question about the bilinear pooling operation

### ISSUE THREAD

**Issue by zerens** [HaoMood/bilinear-cnn#14]
in the `forward` function of BCNN class, the bilinear operation is 

`X = torch.bmm(X, torch.transpose(X, 1, 2)) / (28**2)  # Bilinear`

why does it require the result of matrix multiplication being divided by (28 ** 2)?

**Comment by HaoMood** [comment]
It is mainly to keep up with the authors' following paper: Improved Bilinear Pooling with CNNs.

![image](https://user-images.githubusercontent.com/4077669/51382769-9f932680-1b52-11e9-9ca3-8a49e4d18dae.png)

However, since the bilinear results will be L2-normalized in the subsequent step, diving by 28**2 or not is not important.
